-- CreateTable
CREATE TABLE "consumption_sessions" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "date" TEXT NOT NULL,
    "time" TEXT NOT NULL,
    "location" TEXT NOT NULL,
    "latitude" REAL,
    "longitude" REAL,
    "who_with" TEXT NOT NULL,
    "vessel" TEXT NOT NULL,
    "accessory_used" TEXT NOT NULL,
    "my_vessel" BOOLEAN NOT NULL DEFAULT true,
    "my_substance" BOOLEAN NOT NULL DEFAULT true,
    "strain_name" TEXT NOT NULL,
    "thc_percentage" REAL,
    "purchased_legally" BOOLEAN NOT NULL DEFAULT true,
    "state_purchased" TEXT,
    "tobacco" BOOLEAN NOT NULL DEFAULT false,
    "kief" BOOLEAN NOT NULL DEFAULT false,
    "concentrate" BOOLEAN NOT NULL DEFAULT false,
    "quantity" TEXT NOT NULL,
    "quantity_legacy" REAL,
    "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" DATETIME NOT NULL
);
